# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  bookstorecore:
    build:
      context: "/Users/kilzdavi/Projects/BookStoreCore"
      dockerfile: "BookStoreCore/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/BookStoreCore.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net6.0/BookStoreCore.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/Users/kilzdavi/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/Users/kilzdavi/.nuget/packages"
    image: "bookstorecore:dev"
    ports: []
    volumes:
    - "/Users/kilzdavi/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/Users/kilzdavi/Projects/BookStoreCore/BookStoreCore:/app:rw"
    - "/Users/kilzdavi/Projects/BookStoreCore:/src:rw"
    working_dir: "/app"
