version: '3.4'

services:
  bookstorecore:
    container_name: bookstorecore
    image: ${DOCKER_REGISTRY-}bookstorecore
    build:
      context: .
      dockerfile: BookStoreCore/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://adot:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-sampleapp-bookstorecore
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - fluentbit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql/data #mounting the named storage volume for the DB
    environment: # Accept the license and set sa password. 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password123!


      # ADOT Collector
  aws-otel-collector:
    container_name: adot
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=/etc/otel-config.yaml"]
    environment:
      - AWS_REGION=us-east-1
      - AWS_PROFILE=default
      # Either uncomment and define these:
      #
      # - AWS_PROFILE=<profile>
      # - AWS_ACCESS_KEY_ID=<to_be_added>
      # - AWS_SECRET_ACCESS_KEY=<to_be_added>
      #
      # Or define a profile available in your shared credentials file 
    volumes:
      - ./BookStoreCore/otel-config.yaml:/etc/otel-config.yaml
      - ~/.aws:/root/.aws
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"

  fluentbit:
    container_name: fluentbit
    image: amazon/aws-for-fluent-bit
    environment:
      - AWS_REGION=us-east-1
      - AWS_PROFILE=default
      - HOME=/root
      - AWS_CONFIG_FILE=/root/.aws/config
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
    volumes:
      - ~/.aws/config:/root/.aws/config
      - ~/.aws/credentials:/root/.aws/credentials
    ports:
      - "24224:24224"
      - "24224:24224/udp"


  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
        - ./BookStoreCore/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"

volumes:
   mssql:
    # external: true # External disk to use an existing volume