AWSTemplateFormatVersion: "2010-09-09"
Description: Creates and configures cognito resources for the demo application.
Parameters:
  AuthName:
    Type: String
    Description: Unique Auth Name for Cognito Resources

Resources:
  DemoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: NetCoreDemoAppUsersv1
      UsernameConfiguration:
        CaseSensitive: False
      Schema:
        - Name: email
          Required: True
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: Your verification code is {####}.
      EmailVerificationSubject: Your verification code
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: Your verification code is {####}.
        EmailSubject: Your verification code

  DemoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: NetCoreDemoAppClientv1
      AllowedOAuthFlowsUserPoolClient: True
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      RefreshTokenValidity: "30"
      UserPoolId:
        Ref: DemoUserPool
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://localhost:44314/signin-oidc
      LogoutURLs:
        - https://localhost:44314
      PreventUserExistenceErrors: ENABLED
  DemoUserPoolDomain:
    Type: "AWS::Cognito::UserPoolDomain"
    Properties:
      Domain:
        "Fn::Sub": "${AuthName}-demoappclient"
      UserPoolId:
        Ref: DemoUserPool
Outputs:
  UserPoolId:
    Description: Id of api user pool
    Value:
      Ref: DemoUserPool
    Export:
      Name: local-UserPoolId
  UserPoolClientId:
    Description: Id of api user pool client
    Value:
      Ref: DemoUserPoolClient
    Export:
      Name: local-UserPoolClientId
  UserPoolDomain:
    Description: UserPoolDomain name
    Value:
      Ref: DemoUserPoolDomain
    Export:
      Name: local-UserPoolDomain
  DemoRegion:
    Description: AWS Region name
    Value:
      Ref: "AWS::Region"

